# Site settings
title: Christopher Aicher
email: aicherc [at] uw [dot] edu
description: > # this means to ignore newlines until "baseurl:"   
    Christopher Aicher's Academic Website.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://aicherc.github.io" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
permalink: pretty
highlighter: pygments

