# Site settings
title: Christopher Aicher
email: aicherc [at] uw [dot] edu
googlescholar: https://scholar.google.com/citations?user=UWwqmrkAAAAJ&hl=en
github: aicherc
linkedin: aicherc
description: > # this means to ignore newlines until "baseurl:"
    My Academic Website.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://aicherc.github.io" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet #kramdown
permalink: pretty
highlighter: pygments

gems:
  - jekyll-sitemap
  - jekyll/scholar

# Jekyll Scholar Bibtex Formatting
scholar:
  style: apa
  locale: en

  sort_by: year, month
  order: descending

  source: ./_bibliography
  bibliography: pubs.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

#  details_dir:    bibliography
#  details_layout: bib_details.html
#  details_link:   " Details"

  query: "@*"

  repository: ./pdf

# Other Stuff
exclude: ["Gemfile", "README.md", "build.sh", "deploy-to-master.sh"]
